"""Move class - defines a neighborhood move for tabu search."""

from enum import IntEnum
from typing import Optional
import sys


class MoveType(IntEnum):
    """Move type enumeration."""
    INVALID = -1
    INS = 0      # Insert move
    INTRA_SW = 1  # Intra-vehicle swap
    INTER_SW = 2  # Inter-vehicle swap


class Move:
    """
    A class to define a neighborhood Move.
    
    This class defines a move object that can be placed on the Tabu list
    and/or can be applied to a given solution to transform it to a new state.
    Setting attributes to -1 means they are undefined and should be ignored.
    
    Move types:
    - Ins (insert): remove a nid from vid1 at pos1 and insert it into vid2 at pos2
    - InterSw (inter vehicle swap): exchange nodes between two vehicles
    - IntraSw (intra vehicle swap): exchange nodes in the same vehicle
    
    Note: vid1 and vid2 are NOT vehicle ids, they are positions in the fleet vector.
    """
    
    def __init__(
        self,
        mtype: MoveType = MoveType.INVALID,
        nid1: int = -1,
        nid2: int = -1,
        vid1: int = -1,
        vid2: int = -1,
        pos1: int = -1,
        pos2: int = -1,
        savings: float = -sys.float_info.max
    ):
        """Initialize a Move.
        
        Args:
            mtype: Type of move
            nid1: Node id of first node
            nid2: Node id of second node (if working with 2 nodes)
            vid1: Vehicle 1 position in fleet vector
            vid2: Vehicle 2 position in fleet vector
            pos1: nid1 position in vehicle at vid1
            pos2: nid2 position in vehicle at vid2
            savings: The savings generated by this move
        """
        self.mtype: MoveType = mtype
        self.nid1: int = nid1
        self.nid2: int = nid2
        self.vid1: int = vid1
        self.vid2: int = vid2
        self.pos1: int = pos1
        self.pos2: int = pos2
        self.savings: float = savings
    
    def set_ins_move(
        self,
        from_truck: int,
        from_pos: int,
        from_id: int,
        to_truck: int,
        to_pos: int,
        save: float
    ) -> None:
        """Set move as an Insert move."""
        self.vid1 = from_truck
        self.pos1 = from_pos
        self.nid1 = from_id
        self.vid2 = to_truck
        self.pos2 = to_pos
        self.nid2 = from_id
        self.savings = save
        self.mtype = MoveType.INS
    
    def set_intra_sw_move(
        self,
        from_truck: int,
        from_pos: int,
        from_id: int,
        with_pos: int,
        with_id: int,
        save: float
    ) -> None:
        """Set move as an Intra-vehicle swap move."""
        self.vid1 = from_truck
        self.pos1 = from_pos
        self.nid1 = from_id
        self.vid2 = from_truck
        self.pos2 = with_pos
        self.nid2 = with_id
        self.savings = save
        self.mtype = MoveType.INTRA_SW
    
    def set_inter_sw_move(
        self,
        from_truck: int,
        from_pos: int,
        from_id: int,
        with_truck: int,
        with_pos: int,
        with_id: int,
        save: float
    ) -> None:
        """Set move as an Inter-vehicle swap move."""
        self.vid1 = from_truck
        self.pos1 = from_pos
        self.nid1 = from_id
        self.vid2 = with_truck
        self.pos2 = with_pos
        self.nid2 = with_id
        self.savings = save
        self.mtype = MoveType.INTER_SW
    
    # Type checks
    def is_ins(self) -> bool:
        """Check if move is an Insert move."""
        return self.mtype == MoveType.INS
    
    def is_intra_sw(self) -> bool:
        """Check if move is an Intra-vehicle swap."""
        return self.mtype == MoveType.INTRA_SW
    
    def is_inter_sw(self) -> bool:
        """Check if move is an Inter-vehicle swap."""
        return self.mtype == MoveType.INTER_SW
    
    # Getters for Ins moves
    def get_ins_nid(self) -> int:
        """Get node id for Insert move."""
        return self.nid1
    
    def get_ins_from_truck(self) -> int:
        """Get source truck for Insert move."""
        if self.mtype != MoveType.INS:
            raise ValueError("Move is not an Insert move")
        return self.vid1
    
    def get_ins_to_truck(self) -> int:
        """Get destination truck for Insert move."""
        if self.mtype != MoveType.INS:
            raise ValueError("Move is not an Insert move")
        return self.vid2
    
    def get_ins_from_pos(self) -> int:
        """Get source position for Insert move."""
        if self.mtype != MoveType.INS:
            raise ValueError("Move is not an Insert move")
        return self.pos1
    
    def get_ins_to_pos(self) -> int:
        """Get destination position for Insert move."""
        if self.mtype != MoveType.INS:
            raise ValueError("Move is not an Insert move")
        return self.pos2
    
    # Getters for IntraSw moves
    def get_intra_sw_truck(self) -> int:
        """Get truck for Intra-vehicle swap."""
        if self.mtype != MoveType.INTRA_SW:
            raise ValueError("Move is not an Intra-vehicle swap")
        return self.vid1
    
    def get_intra_sw_from_pos(self) -> int:
        """Get first position for Intra-vehicle swap."""
        if self.mtype != MoveType.INTRA_SW:
            raise ValueError("Move is not an Intra-vehicle swap")
        return self.pos1
    
    def get_intra_sw_to_pos(self) -> int:
        """Get second position for Intra-vehicle swap."""
        if self.mtype != MoveType.INTRA_SW:
            raise ValueError("Move is not an Intra-vehicle swap")
        return self.pos2
    
    def get_intra_sw_nid1(self) -> int:
        """Get first node id for Intra-vehicle swap."""
        return self.nid1
    
    def get_intra_sw_nid2(self) -> int:
        """Get second node id for Intra-vehicle swap."""
        return self.nid2
    
    # Getters for InterSw moves
    def get_inter_sw_truck1(self) -> int:
        """Get first truck for Inter-vehicle swap."""
        if self.mtype != MoveType.INTER_SW:
            raise ValueError("Move is not an Inter-vehicle swap")
        return self.vid1
    
    def get_inter_sw_from_pos(self) -> int:
        """Get position in first truck for Inter-vehicle swap."""
        if self.mtype != MoveType.INTER_SW:
            raise ValueError("Move is not an Inter-vehicle swap")
        return self.pos1
    
    def get_inter_sw_truck2(self) -> int:
        """Get second truck for Inter-vehicle swap."""
        if self.mtype != MoveType.INTER_SW:
            raise ValueError("Move is not an Inter-vehicle swap")
        return self.vid2
    
    def get_inter_sw_to_pos(self) -> int:
        """Get position in second truck for Inter-vehicle swap."""
        if self.mtype != MoveType.INTER_SW:
            raise ValueError("Move is not an Inter-vehicle swap")
        return self.pos2
    
    # Comparison operators
    def __eq__(self, other: object) -> bool:
        """Equality comparison."""
        if not isinstance(other, Move):
            return False
        return (self.nid1 == other.nid1 and
                self.nid2 == other.nid2 and
                self.vid1 == other.vid1 and
                self.vid2 == other.vid2 and
                self.pos1 == other.pos1 and
                self.pos2 == other.pos2)
    
    def __lt__(self, other: 'Move') -> bool:
        """Less than comparison for ordering."""
        if self.nid1 != other.nid1:
            return self.nid1 < other.nid1
        if self.nid2 != other.nid2:
            return self.nid2 < other.nid2
        if self.vid1 != other.vid1:
            return self.vid1 < other.vid1
        if self.pos1 != other.pos1:
            return self.pos1 < other.pos1
        return self.pos2 < other.pos2
    
    def less(self, other: 'Move') -> bool:
        """Less than comparison (alias for __lt__)."""
        return self < other
    
    @staticmethod
    def by_savings(a: 'Move', b: 'Move') -> bool:
        """Compare moves by savings in descending order."""
        if a.savings == b.savings:
            return a < b
        return a.savings > b.savings
    
    @staticmethod
    def by_savings_ascending(a: 'Move', b: 'Move') -> bool:
        """Compare moves by savings in ascending order."""
        return a.savings < b.savings
    
    def is_forbidden(self, tabu: 'Move') -> bool:
        """Check if this move is forbidden based on tabu move.
        
        The isForbidden() test is not associative.
        This test is used to determine if this move would be tabu if
        the given move is on the tabu list.
        """
        if self == tabu:
            return True
        
        if self.mtype == MoveType.INS:
            if self.vid2 == tabu.vid1:
                return True
        elif self.mtype == MoveType.INTRA_SW:
            if (self.nid1 == tabu.nid1 or self.nid2 == tabu.nid2 or
                self.nid1 == tabu.nid2 or self.nid2 == tabu.nid1):
                return True
        elif self.mtype == MoveType.INTER_SW:
            if (self.nid1 == tabu.nid1 or self.nid2 == tabu.nid2 or
                self.nid1 == tabu.nid2 or self.nid2 == tabu.nid1):
                return True
        
        return False
    
    def is_tabu(self, move_e: 'Move', rule: Optional[int] = None) -> bool:
        """Check if move is tabu based on another move.
        
        Args:
            move_e: Move to check against
            rule: Optional rule number (for Ins moves)
            
        Returns:
            True if move is tabu
        """
        if self.mtype != move_e.mtype:
            return False
        
        if self.mtype == MoveType.INVALID:
            return False
        
        if self.mtype == MoveType.INS:
            if rule is None:
                rule = 5  # Default rule for Ins
            return self._ins_forbidden(move_e, rule)
        elif self.mtype == MoveType.INTRA_SW:
            return move_e.is_forbidden(self)
        elif self.mtype == MoveType.INTER_SW:
            return move_e.is_forbidden(self)
        
        return False
    
    def _ins_forbidden(self, move_e: 'Move', rule: int) -> bool:
        """Check if Ins move is forbidden based on rule.
        
        Args:
            move_e: Move to evaluate
            rule: Rule number (0-6)
            
        Returns:
            True if move is forbidden
        """
        if move_e.mtype != MoveType.INS:
            return False
        
        if rule == 0:
            return self._ins_forbidden_rule0(move_e)
        elif rule == 1:
            return self._ins_forbidden_rule1(move_e)
        elif rule == 2:
            return self._ins_forbidden_rule2(move_e)
        elif rule == 3:
            return self._ins_forbidden_rule3(move_e)
        elif rule == 4:
            return self._ins_forbidden_rule4(move_e)
        elif rule == 5:
            return self._ins_forbidden_rule5(move_e)
        elif rule == 6:
            return self._ins_forbidden_rule6(move_e)
        
        return False
    
    def _ins_forbidden_rule0(self, move_e: 'Move') -> bool:
        """Rule 0: Semi inverse move is prohibited."""
        return (move_e.get_ins_nid() == self.get_ins_nid() and
                move_e.get_ins_from_truck() == self.get_ins_to_truck() and
                move_e.get_ins_to_truck() == self.get_ins_from_truck())
    
    def _ins_forbidden_rule1(self, move_e: 'Move') -> bool:
        """Rule 1: Forbidding moving container back to original truck."""
        return (move_e.get_ins_nid() == self.get_ins_nid() and
                move_e.get_ins_from_truck() == self.get_ins_to_truck())
    
    def _ins_forbidden_rule2(self, move_e: 'Move') -> bool:
        """Rule 2: Forbidding inserting to truck we inserted from."""
        return (move_e.get_ins_from_truck() == self.get_ins_to_truck() and
                move_e.get_ins_to_truck() == self.get_ins_from_truck())
    
    def _ins_forbidden_rule3(self, move_e: 'Move') -> bool:
        """Rule 3: Forbidding reinserting container back to original truck."""
        return (move_e.get_ins_nid() == self.get_ins_nid() and
                move_e.get_ins_to_truck() == self.get_ins_from_truck())
    
    def _ins_forbidden_rule4(self, move_e: 'Move') -> bool:
        """Rule 4: Forbidding to move a container recently moved."""
        return move_e.get_ins_nid() == self.get_ins_nid()
    
    def _ins_forbidden_rule5(self, move_e: 'Move') -> bool:
        """Rule 5: Forbidding to remove from recently inserted truck."""
        return move_e.get_ins_from_truck() == self.get_ins_to_truck()
    
    def _ins_forbidden_rule6(self, move_e: 'Move') -> bool:
        """Rule 6: Forbidding to reinsert to truck we removed from."""
        return move_e.get_ins_to_truck() == self.get_ins_from_truck()
    
    def __repr__(self) -> str:
        """String representation."""
        move_type_str = self.mtype.name if self.mtype != MoveType.INVALID else "Invalid"
        return (f"Move(type={move_type_str}, nid1={self.nid1}, nid2={self.nid2}, "
                f"vid1={self.vid1}, vid2={self.vid2}, pos1={self.pos1}, "
                f"pos2={self.pos2}, savings={self.savings})")

